export * from './auth/Auth';
export * from './homepage/index';
export * from './profile/profile';
export * from './admin/admin';
export * from './admin/addQuiz';
export * from './admin/deleteQuiz'
export * from './admin/alldelquizzes'
export * from './error/error';
export * from './quizPage/QuizPage';
export * from './content/content';
export * from './chat/ChatPage';
